---
title: "HMM-example.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulation

You can also embed plots, for example:

```{r}
agent <- c(0.8, 0.2)
transition <- matrix(c(0.7, 0.3, 0.2, 0.8),
                     nrow=2, byrow=TRUE,
                     dimnames=list(c("Fresh", "Tired"),
                                   c("Fresh", "Tired")))
emission <- matrix(c(0.8, 0.2, 0.4, 0.6), nrow=2, 
                    byrow=TRUE,
                    dimnames=list(c("Fresh", "Tired"),
                                  c("Acceptance", "Rejection")))
```

## Stationary distribution

```{r stationaryBrutalForce}
te <- transition; for (i in 1:100)  te <- te %*% transition
te
transition^100
```

```{r}
stationary <- function(transition) {
    stopifnot(is.matrix(transition) &&
            nrow(transition)==ncol(transition) &&
            all(transition>=0 & transition<=1))
  p <- diag(nrow(transition)) - transition
  A <- rbind(t(p), rep(1, ncol(transition)))
  b <- c(rep(0, nrow(transition)),
         1)
  res <- qr.solve(A, b)
  attr(res, "A") <- A
  attr(res, "b") <- b
  return(res)
} 
stationary(transition)
stationary(matrix(c(0.7, 0.2, 0.1, 0.4, 0.6, 0, 0, 1, 0),
                  nrow=3, byrow=TRUE))
```

# Simulation

```{r simulateHMM}
library(HMM)
hmmModel <- initHMM(States=c("A", "D"), # A=Angel, D=Devil
                    Symbols=c("B", "R"), # B=Blessing, R=Rant
                    startProbs=c(0.5, 0.5),
                    transProbs = matrix(c(0.8, 0.2, 0.2, 0.8), nrow=2),
                    emissionProbs = matrix(c(0.9, 0.1, 0.1, 0.9), nrow=2))
simHmm <- simHMM(hmmModel, 100)
simStates <- paste(simHmm$states, collapse="")
simSymbols <- paste(simHmm$observation, collapse="")
starts <- seq(1, 81, by=20)
ends <- seq(20, 100, by=20)
statesSplit <- sapply(seq(along=starts), 
                      function(i) substr(simStates, starts[i], ends[i]))
symbolsSplit <- sapply(seq(along=starts), 
                      function(i) substr(simSymbols, starts[i], ends[i]))
res <- unlist(lapply(seq(along=starts),
              function(i) c(statesSplit[i], symbolsSplit[i])))
writeLines(res, "simHmm.txt")
```

